(function() {var implementors = {};
implementors["node_runtime"] = [{text:"impl&lt;RuntimeApiImplCall:&nbsp;<a class=\"trait\" href=\"substrate_client/runtime_api/trait.CallRuntimeAt.html\" title=\"trait substrate_client::runtime_api::CallRuntimeAt\">CallRuntimeAt</a>&lt;&lt;<a class=\"struct\" href=\"node_runtime/struct.Runtime.html\" title=\"struct node_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html\" title=\"trait sr_primitives::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sr_primitives::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>&gt; + 'static&gt; <a class=\"trait\" href=\"substrate_consensus_aura_primitives/trait.AuraApi.html\" title=\"trait substrate_consensus_aura_primitives::AuraApi\">AuraApi</a>&lt;&lt;<a class=\"struct\" href=\"node_runtime/struct.Runtime.html\" title=\"struct node_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html\" title=\"trait sr_primitives::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sr_primitives::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>, <a class=\"struct\" href=\"substrate_primitives/ed25519/struct.Public.html\" title=\"struct substrate_primitives::ed25519::Public\">Public</a>&gt; for <a class=\"struct\" href=\"node_runtime/struct.RuntimeApiImpl.html\" title=\"struct node_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;RuntimeApiImplCall&gt;",synthetic:false,types:["node_runtime::RuntimeApiImpl"]},];
implementors["node_template_runtime"] = [{text:"impl&lt;RuntimeApiImplCall:&nbsp;<a class=\"trait\" href=\"substrate_client/runtime_api/trait.CallRuntimeAt.html\" title=\"trait substrate_client::runtime_api::CallRuntimeAt\">CallRuntimeAt</a>&lt;&lt;<a class=\"struct\" href=\"node_template_runtime/struct.Runtime.html\" title=\"struct node_template_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html\" title=\"trait sr_primitives::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sr_primitives::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>&gt; + 'static&gt; <a class=\"trait\" href=\"substrate_consensus_aura_primitives/trait.AuraApi.html\" title=\"trait substrate_consensus_aura_primitives::AuraApi\">AuraApi</a>&lt;&lt;<a class=\"struct\" href=\"node_template_runtime/struct.Runtime.html\" title=\"struct node_template_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html\" title=\"trait sr_primitives::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sr_primitives::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>, <a class=\"struct\" href=\"substrate_primitives/ed25519/struct.Public.html\" title=\"struct substrate_primitives::ed25519::Public\">Public</a>&gt; for <a class=\"struct\" href=\"node_template_runtime/struct.RuntimeApiImpl.html\" title=\"struct node_template_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;RuntimeApiImplCall&gt;",synthetic:false,types:["node_template_runtime::RuntimeApiImpl"]},];
implementors["substrate_test_runtime"] = [{text:"impl&lt;RuntimeApiImplCall:&nbsp;<a class=\"trait\" href=\"substrate_client/runtime_api/trait.CallRuntimeAt.html\" title=\"trait substrate_client::runtime_api::CallRuntimeAt\">CallRuntimeAt</a>&lt;&lt;<a class=\"struct\" href=\"substrate_test_runtime/struct.Runtime.html\" title=\"struct substrate_test_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html\" title=\"trait sr_primitives::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sr_primitives::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>&gt; + 'static&gt; <a class=\"trait\" href=\"substrate_consensus_aura_primitives/trait.AuraApi.html\" title=\"trait substrate_consensus_aura_primitives::AuraApi\">AuraApi</a>&lt;&lt;<a class=\"struct\" href=\"substrate_test_runtime/struct.Runtime.html\" title=\"struct substrate_test_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html\" title=\"trait sr_primitives::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sr_primitives::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>, <a class=\"struct\" href=\"substrate_primitives/sr25519/struct.Public.html\" title=\"struct substrate_primitives::sr25519::Public\">Public</a>&gt; for <a class=\"struct\" href=\"substrate_test_runtime/struct.RuntimeApiImpl.html\" title=\"struct substrate_test_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;RuntimeApiImplCall&gt;",synthetic:false,types:["substrate_test_runtime::RuntimeApiImpl"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
