(function() {var implementors = {};
implementors["bitvec"] = [{"text":"impl&lt;O, V&gt; Not for BitArray&lt;O, V&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;O: BitOrder,<br>&nbsp;&nbsp;&nbsp;&nbsp;V: BitView,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;R&gt; Not for BitMask&lt;R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;R: BitRegister,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;M, O, T&gt; Not for BitRef&lt;'_, M, O, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;M: Mutability,<br>&nbsp;&nbsp;&nbsp;&nbsp;O: BitOrder,<br>&nbsp;&nbsp;&nbsp;&nbsp;T: BitStore,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;'a, O, T&gt; Not for &amp;'a mut BitSlice&lt;O, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;O: BitOrder,<br>&nbsp;&nbsp;&nbsp;&nbsp;T: BitStore,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;O, T&gt; Not for BitBox&lt;O, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;O: BitOrder,<br>&nbsp;&nbsp;&nbsp;&nbsp;T: BitStore,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;O, T&gt; Not for BitVec&lt;O, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;O: BitOrder,<br>&nbsp;&nbsp;&nbsp;&nbsp;T: BitStore,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["enumflags2"] = [{"text":"impl&lt;T&gt; Not for BitFlags&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: RawBitFlags,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["frame_support"] = [{"text":"impl Not for WithdrawReasons","synthetic":false,"types":[]}];
implementors["libp2p_core"] = [{"text":"impl Not for Endpoint","synthetic":false,"types":[]}];
implementors["num_bigint"] = [{"text":"impl Not for BigInt","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Not for &amp;'a BigInt","synthetic":false,"types":[]}];
implementors["pallet_contracts_primitives"] = [{"text":"impl Not for ReturnFlags","synthetic":false,"types":[]}];
implementors["pallet_identity"] = [{"text":"impl Not for IdentityField","synthetic":false,"types":[]}];
implementors["primitive_types"] = [{"text":"impl Not for U128","synthetic":false,"types":[]},{"text":"impl Not for U256","synthetic":false,"types":[]},{"text":"impl Not for U512","synthetic":false,"types":[]}];
implementors["region"] = [{"text":"impl Not for Protection","synthetic":false,"types":[]}];
implementors["subtle"] = [{"text":"impl Not for Choice","synthetic":false,"types":[]}];
implementors["typenum"] = [{"text":"impl Not for B0","synthetic":false,"types":[]},{"text":"impl Not for B1","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()