(function() {var implementors = {};
implementors["substrate_client"] = [{text:"impl&lt;Block, H&gt; <a class=\"trait\" href=\"substrate_state_machine/changes_trie/trait.Storage.html\" title=\"trait substrate_state_machine::changes_trie::Storage\">Storage</a>&lt;H, &lt;&lt;Block as <a class=\"trait\" href=\"sr_primitives/traits/trait.Block.html\" title=\"trait sr_primitives::traits::Block\">Block</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.Block.html#associatedtype.Header\" title=\"type sr_primitives::traits::Block::Header\">Header</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.Header.html\" title=\"trait sr_primitives::traits::Header\">Header</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.Header.html#associatedtype.Number\" title=\"type sr_primitives::traits::Header::Number\">Number</a>&gt; for <a class=\"struct\" href=\"substrate_client/in_mem/struct.ChangesTrieStorage.html\" title=\"struct substrate_client::in_mem::ChangesTrieStorage\">ChangesTrieStorage</a>&lt;Block, H&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Block: <a class=\"trait\" href=\"sr_primitives/traits/trait.Block.html\" title=\"trait sr_primitives::traits::Block\">BlockT</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;H: <a class=\"trait\" href=\"hash_db/trait.Hasher.html\" title=\"trait hash_db::Hasher\">Hasher</a>,&nbsp;</span>",synthetic:false,types:["substrate_client::in_mem::ChangesTrieStorage"]},];
implementors["substrate_client_db"] = [{text:"impl&lt;Block&gt; <a class=\"trait\" href=\"substrate_state_machine/changes_trie/trait.Storage.html\" title=\"trait substrate_state_machine::changes_trie::Storage\">Storage</a>&lt;<a class=\"struct\" href=\"substrate_primitives/hasher/blake2/struct.Blake2Hasher.html\" title=\"struct substrate_primitives::hasher::blake2::Blake2Hasher\">Blake2Hasher</a>, &lt;&lt;Block as <a class=\"trait\" href=\"sr_primitives/traits/trait.Block.html\" title=\"trait sr_primitives::traits::Block\">Block</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.Block.html#associatedtype.Header\" title=\"type sr_primitives::traits::Block::Header\">Header</a> as <a class=\"trait\" href=\"sr_primitives/traits/trait.Header.html\" title=\"trait sr_primitives::traits::Header\">Header</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.Header.html#associatedtype.Number\" title=\"type sr_primitives::traits::Header::Number\">Number</a>&gt; for <a class=\"struct\" href=\"substrate_client_db/struct.DbChangesTrieStorage.html\" title=\"struct substrate_client_db::DbChangesTrieStorage\">DbChangesTrieStorage</a>&lt;Block&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Block: <a class=\"trait\" href=\"sr_primitives/traits/trait.Block.html\" title=\"trait sr_primitives::traits::Block\">BlockT</a>&lt;Hash = <a class=\"struct\" href=\"primitive_types/struct.H256.html\" title=\"struct primitive_types::H256\">H256</a>&gt;,&nbsp;</span>",synthetic:false,types:["substrate_client_db::DbChangesTrieStorage"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
