(function() {var implementors = {};
implementors["substrate_consensus_common"] = [];
implementors["substrate_network"] = [{text:"impl&lt;B:&nbsp;<a class=\"trait\" href=\"sr_primitives/traits/trait.Block.html\" title=\"trait sr_primitives::traits::Block\">BlockT</a>&gt; <a class=\"trait\" href=\"substrate_consensus_common/import_queue/trait.Link.html\" title=\"trait substrate_consensus_common::import_queue::Link\">Link</a>&lt;B&gt; for <a class=\"struct\" href=\"substrate_network/test/struct.NoopLink.html\" title=\"struct substrate_network::test::NoopLink\">NoopLink</a>",synthetic:false,types:["substrate_network::test::NoopLink"]},{text:"impl&lt;B:&nbsp;<a class=\"trait\" href=\"sr_primitives/traits/trait.Block.html\" title=\"trait sr_primitives::traits::Block\">BlockT</a>, S:&nbsp;<a class=\"trait\" href=\"substrate_network/specialization/trait.NetworkSpecialization.html\" title=\"trait substrate_network::specialization::NetworkSpecialization\">NetworkSpecialization</a>&lt;B&gt;&gt; <a class=\"trait\" href=\"substrate_consensus_common/import_queue/trait.Link.html\" title=\"trait substrate_consensus_common::import_queue::Link\">Link</a>&lt;B&gt; for <a class=\"struct\" href=\"substrate_network/test/struct.NetworkLink.html\" title=\"struct substrate_network::test::NetworkLink\">NetworkLink</a>&lt;B, S&gt;",synthetic:false,types:["substrate_network::test::NetworkLink"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"substrate_network/specialization/trait.NetworkSpecialization.html\" title=\"trait substrate_network::specialization::NetworkSpecialization\">NetworkSpecialization</a>&lt;<a class=\"type\" href=\"substrate_network/test/type.Block.html\" title=\"type substrate_network::test::Block\">Block</a>&gt;&gt; <a class=\"trait\" href=\"substrate_consensus_common/import_queue/trait.Link.html\" title=\"trait substrate_consensus_common::import_queue::Link\">Link</a>&lt;<a class=\"struct\" href=\"sr_primitives/generic/block/struct.Block.html\" title=\"struct sr_primitives::generic::block::Block\">Block</a>&lt;<a class=\"struct\" href=\"sr_primitives/generic/header/struct.Header.html\" title=\"struct sr_primitives::generic::header::Header\">Header</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u64.html\">u64</a>, <a class=\"struct\" href=\"sr_primitives/traits/struct.BlakeTwo256.html\" title=\"struct sr_primitives::traits::BlakeTwo256\">BlakeTwo256</a>&gt;, <a class=\"enum\" href=\"substrate_network/test/enum.Extrinsic.html\" title=\"enum substrate_network::test::Extrinsic\">Extrinsic</a>&gt;&gt; for <a class=\"struct\" href=\"substrate_network/test/struct.TestLink.html\" title=\"struct substrate_network::test::TestLink\">TestLink</a>&lt;S&gt;",synthetic:false,types:["substrate_network::test::TestLink"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
