(function() {var implementors = {};
implementors["node_template_runtime"] = [{text:"impl&lt;RuntimeApiImplCall:&nbsp;<a class=\"trait\" href=\"sp_api/trait.CallRuntimeAt.html\" title=\"trait sp_api::CallRuntimeAt\">CallRuntimeAt</a>&lt;&lt;<a class=\"struct\" href=\"node_template_runtime/struct.Runtime.html\" title=\"struct node_template_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html\" title=\"trait sp_runtime::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sp_runtime::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>&gt; + 'static&gt; <a class=\"trait\" href=\"sp_consensus_aura/trait.AuraApi.html\" title=\"trait sp_consensus_aura::AuraApi\">AuraApi</a>&lt;&lt;<a class=\"struct\" href=\"node_template_runtime/struct.Runtime.html\" title=\"struct node_template_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html\" title=\"trait sp_runtime::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sp_runtime::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>, Public&gt; for <a class=\"struct\" href=\"node_template_runtime/struct.RuntimeApiImpl.html\" title=\"struct node_template_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;RuntimeApiImplCall&gt;",synthetic:false,types:["node_template_runtime::RuntimeApiImpl"]},];
implementors["substrate_test_runtime"] = [{text:"impl&lt;RuntimeApiImplCall:&nbsp;<a class=\"trait\" href=\"sp_api/trait.CallRuntimeAt.html\" title=\"trait sp_api::CallRuntimeAt\">CallRuntimeAt</a>&lt;&lt;<a class=\"struct\" href=\"substrate_test_runtime/struct.Runtime.html\" title=\"struct substrate_test_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html\" title=\"trait sp_runtime::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sp_runtime::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>&gt; + 'static&gt; <a class=\"trait\" href=\"sp_consensus_aura/trait.AuraApi.html\" title=\"trait sp_consensus_aura::AuraApi\">AuraApi</a>&lt;&lt;<a class=\"struct\" href=\"substrate_test_runtime/struct.Runtime.html\" title=\"struct substrate_test_runtime::Runtime\">Runtime</a> as <a class=\"trait\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html\" title=\"trait sp_runtime::traits::GetNodeBlockType\">GetNodeBlockType</a>&gt;::<a class=\"type\" href=\"sp_runtime/traits/trait.GetNodeBlockType.html#associatedtype.NodeBlock\" title=\"type sp_runtime::traits::GetNodeBlockType::NodeBlock\">NodeBlock</a>, Public&gt; for <a class=\"struct\" href=\"substrate_test_runtime/struct.RuntimeApiImpl.html\" title=\"struct substrate_test_runtime::RuntimeApiImpl\">RuntimeApiImpl</a>&lt;RuntimeApiImplCall&gt;",synthetic:false,types:["substrate_test_runtime::RuntimeApiImpl"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()