(function() {var implementors = {};
implementors["curve25519_dalek"] = [{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"curve25519_dalek/scalar/struct.Scalar.html\" title=\"struct curve25519_dalek::scalar::Scalar\">Scalar</a>",synthetic:false,types:["curve25519_dalek::scalar::Scalar"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"curve25519_dalek/montgomery/struct.MontgomeryPoint.html\" title=\"struct curve25519_dalek::montgomery::MontgomeryPoint\">MontgomeryPoint</a>",synthetic:false,types:["curve25519_dalek::montgomery::MontgomeryPoint"]},];
implementors["libp2p_noise"] = [{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"libp2p_noise/struct.X25519.html\" title=\"struct libp2p_noise::X25519\">X25519</a>",synthetic:false,types:["libp2p_noise::protocol::x25519::X25519"]},];
implementors["merlin"] = [{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"merlin/struct.Transcript.html\" title=\"struct merlin::Transcript\">Transcript</a>",synthetic:false,types:["merlin::transcript::Transcript"]},];
implementors["schnorrkel"] = [{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/points/struct.RistrettoBoth.html\" title=\"struct schnorrkel::points::RistrettoBoth\">RistrettoBoth</a>",synthetic:false,types:["schnorrkel::points::RistrettoBoth"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.MiniSecretKey.html\" title=\"struct schnorrkel::keys::MiniSecretKey\">MiniSecretKey</a>",synthetic:false,types:["schnorrkel::keys::MiniSecretKey"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.SecretKey.html\" title=\"struct schnorrkel::keys::SecretKey\">SecretKey</a>",synthetic:false,types:["schnorrkel::keys::SecretKey"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.PublicKey.html\" title=\"struct schnorrkel::keys::PublicKey\">PublicKey</a>",synthetic:false,types:["schnorrkel::keys::PublicKey"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.Keypair.html\" title=\"struct schnorrkel::keys::Keypair\">Keypair</a>",synthetic:false,types:["schnorrkel::keys::Keypair"]},];
implementors["sp_core"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a>&gt; <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"sp_core/crypto/struct.Protected.html\" title=\"struct sp_core::crypto::Protected\">Protected</a>&lt;T&gt;",synthetic:false,types:["sp_core::crypto::Protected"]},];
implementors["zeroize"] = [];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()