(function() {var implementors = {};
implementors["libp2p_noise"] = [{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"libp2p_noise/struct.X25519.html\" title=\"struct libp2p_noise::X25519\">X25519</a>",synthetic:false,types:["libp2p_noise::protocol::x25519::X25519"]},];
implementors["schnorrkel"] = [{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/points/struct.RistrettoBoth.html\" title=\"struct schnorrkel::points::RistrettoBoth\">RistrettoBoth</a>",synthetic:false,types:["schnorrkel::points::RistrettoBoth"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.MiniSecretKey.html\" title=\"struct schnorrkel::keys::MiniSecretKey\">MiniSecretKey</a>",synthetic:false,types:["schnorrkel::keys::MiniSecretKey"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.SecretKey.html\" title=\"struct schnorrkel::keys::SecretKey\">SecretKey</a>",synthetic:false,types:["schnorrkel::keys::SecretKey"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.PublicKey.html\" title=\"struct schnorrkel::keys::PublicKey\">PublicKey</a>",synthetic:false,types:["schnorrkel::keys::PublicKey"]},{text:"impl <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"schnorrkel/keys/struct.Keypair.html\" title=\"struct schnorrkel::keys::Keypair\">Keypair</a>",synthetic:false,types:["schnorrkel::keys::Keypair"]},];
implementors["substrate_primitives"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a>&gt; <a class=\"trait\" href=\"zeroize/trait.Zeroize.html\" title=\"trait zeroize::Zeroize\">Zeroize</a> for <a class=\"struct\" href=\"substrate_primitives/crypto/struct.Protected.html\" title=\"struct substrate_primitives::crypto::Protected\">Protected</a>&lt;T&gt;",synthetic:false,types:["substrate_primitives::crypto::Protected"]},];
implementors["zeroize"] = [];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()