(function() {var implementors = {};
implementors["substrate_application_crypto"] = [{text:"impl <a class=\"trait\" href=\"substrate_primitives/crypto/trait.Wraps.html\" title=\"trait substrate_primitives::crypto::Wraps\">Wraps</a> for <a class=\"struct\" href=\"substrate_application_crypto/ed25519/struct.AppPublic.html\" title=\"struct substrate_application_crypto::ed25519::AppPublic\">Public</a>",synthetic:false,types:["substrate_application_crypto::ed25519::app::Public"]},{text:"impl <a class=\"trait\" href=\"substrate_primitives/crypto/trait.Wraps.html\" title=\"trait substrate_primitives::crypto::Wraps\">Wraps</a> for <a class=\"struct\" href=\"substrate_application_crypto/ed25519/struct.AppSignature.html\" title=\"struct substrate_application_crypto::ed25519::AppSignature\">Signature</a>",synthetic:false,types:["substrate_application_crypto::ed25519::app::Signature"]},{text:"impl <a class=\"trait\" href=\"substrate_primitives/crypto/trait.Wraps.html\" title=\"trait substrate_primitives::crypto::Wraps\">Wraps</a> for <a class=\"struct\" href=\"substrate_application_crypto/ed25519/struct.AppPair.html\" title=\"struct substrate_application_crypto::ed25519::AppPair\">Pair</a>",synthetic:false,types:["substrate_application_crypto::ed25519::app::Pair"]},{text:"impl <a class=\"trait\" href=\"substrate_primitives/crypto/trait.Wraps.html\" title=\"trait substrate_primitives::crypto::Wraps\">Wraps</a> for <a class=\"struct\" href=\"substrate_application_crypto/sr25519/struct.AppPublic.html\" title=\"struct substrate_application_crypto::sr25519::AppPublic\">Public</a>",synthetic:false,types:["substrate_application_crypto::sr25519::app::Public"]},{text:"impl <a class=\"trait\" href=\"substrate_primitives/crypto/trait.Wraps.html\" title=\"trait substrate_primitives::crypto::Wraps\">Wraps</a> for <a class=\"struct\" href=\"substrate_application_crypto/sr25519/struct.AppSignature.html\" title=\"struct substrate_application_crypto::sr25519::AppSignature\">Signature</a>",synthetic:false,types:["substrate_application_crypto::sr25519::app::Signature"]},{text:"impl <a class=\"trait\" href=\"substrate_primitives/crypto/trait.Wraps.html\" title=\"trait substrate_primitives::crypto::Wraps\">Wraps</a> for <a class=\"struct\" href=\"substrate_application_crypto/sr25519/struct.AppPair.html\" title=\"struct substrate_application_crypto::sr25519::AppPair\">Pair</a>",synthetic:false,types:["substrate_application_crypto::sr25519::app::Pair"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
