(function() {var implementors = {};
implementors["futures_channel"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_channel/oneshot/struct.Receiver.html\" title=\"struct futures_channel::oneshot::Receiver\">Receiver</a>&lt;T&gt;",synthetic:false,types:["futures_channel::oneshot::Receiver"]},];
implementors["futures_timer"] = [{text:"impl&lt;F&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_timer/ext/struct.Timeout.html\" title=\"struct futures_timer::ext::Timeout\">Timeout</a>&lt;F&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;F: <a class=\"trait\" href=\"futures_core/future/trait.TryFuture.html\" title=\"trait futures_core::future::TryFuture\">TryFuture</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;F::<a class=\"type\" href=\"futures_core/future/trait.TryFuture.html#associatedtype.Error\" title=\"type futures_core::future::TryFuture::Error\">Error</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt;,&nbsp;</span>",synthetic:false,types:["futures_timer::ext::Timeout"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_timer/struct.Delay.html\" title=\"struct futures_timer::Delay\">Delay</a>",synthetic:false,types:["futures_timer::delay::Delay"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"futures_timer/struct.Timer.html\" title=\"struct futures_timer::Timer\">Timer</a>",synthetic:false,types:["futures_timer::Timer"]},];
implementors["substrate_authority_discovery"] = [{text:"impl&lt;Client, Network, Block&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a> for <a class=\"struct\" href=\"substrate_authority_discovery/struct.AuthorityDiscovery.html\" title=\"struct substrate_authority_discovery::AuthorityDiscovery\">AuthorityDiscovery</a>&lt;Client, Network, Block&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Block: <a class=\"trait\" href=\"sr_primitives/traits/trait.Block.html\" title=\"trait sr_primitives::traits::Block\">BlockT</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;Network: <a class=\"trait\" href=\"substrate_authority_discovery/trait.NetworkProvider.html\" title=\"trait substrate_authority_discovery::NetworkProvider\">NetworkProvider</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;Client: <a class=\"trait\" href=\"sr_primitives/traits/trait.ProvideRuntimeApi.html\" title=\"trait sr_primitives::traits::ProvideRuntimeApi\">ProvideRuntimeApi</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static + <a class=\"trait\" href=\"substrate_client/blockchain/trait.HeaderBackend.html\" title=\"trait substrate_client::blockchain::HeaderBackend\">HeaderBackend</a>&lt;Block&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;Client as <a class=\"trait\" href=\"sr_primitives/traits/trait.ProvideRuntimeApi.html\" title=\"trait sr_primitives::traits::ProvideRuntimeApi\">ProvideRuntimeApi</a>&gt;::<a class=\"type\" href=\"sr_primitives/traits/trait.ProvideRuntimeApi.html#associatedtype.Api\" title=\"type sr_primitives::traits::ProvideRuntimeApi::Api\">Api</a>: <a class=\"trait\" href=\"substrate_authority_discovery_primitives/trait.AuthorityDiscoveryApi.html\" title=\"trait substrate_authority_discovery_primitives::AuthorityDiscoveryApi\">AuthorityDiscoveryApi</a>&lt;Block&gt;,&nbsp;</span>",synthetic:false,types:["substrate_authority_discovery::AuthorityDiscovery"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()